const $=id=>document.getElementById(id);const defaultData={packages:[["Package 03","20","700"],["Package 04","25","800"],["Package 05","40","1000"]],services:[["Super Fast","High-speed broadband"],["Fast & Reliable","Stable internet service"],["24/7 Support","Professional support"]],media:[["Circle FTP","Unlimited speed"],["Movies World FTP","Unlimited speed"],["BAS FTP","Unlimited speed"],["ICC","Unlimited speed"],["WOW","Unlimited speed"],["Sam Online","Unlimited speed"]]};
let data=JSON.parse(localStorage.getItem("ntl_admin")||"null")||defaultData;function save(){localStorage.setItem("ntl_admin",JSON.stringify(data))}
function login(){if($("user").value==="admin"&&$("pass").value==="admin123"){$("login").classList.add("hidden");$("app").classList.remove("hidden");show("dashboard")}else alert("Invalid login")}
function logout(){location.reload()}
function show(page){document.querySelectorAll(".navitem").forEach(x=>x.classList.remove("active"));document.getElementById("title").textContent=page[0].toUpperCase()+page.slice(1);let c=$("content");
if(page==="dashboard"){let leads=JSON.parse(localStorage.getItem("ntl_leads")||"[]");c.innerHTML=`<div class="metricgrid"><div class="metric"><small>Packages</small><strong>${data.packages.length}</strong></div><div class="metric"><small>Services</small><strong>${data.services.length}</strong></div><div class="metric"><small>Media Servers</small><strong>${data.media.length}</strong></div><div class="metric"><small>New Leads</small><strong>${leads.length}</strong></div></div><div class="panel"><h3>Quick control</h3><p>Edit packages, services, media servers and customer requests from this dashboard.</p></div>`}
else if(["packages","services","media"].includes(page)){let key=page==="packages"?"packages":page;renderEditor(c,key)}
else if(page==="leads"){let leads=JSON.parse(localStorage.getItem("ntl_leads")||"[]");c.innerHTML=`<div class="panel"><h3>Connection Requests</h3>${leads.length?leads.map((l,i)=>`<div class="row"><div><b>${l.name}</b><br><small>${l.phone} · ${l.address} · ${l.time}</small></div><button class="danger" onclick="delLead(${i})">Delete</button></div>`).join(""):"<p>No leads yet.</p>"}</div>`}
else{c.innerHTML=`<div class="panel"><h3>Site Settings</h3><p>For production, move authentication and data to a server-side database. This demo stores settings in the browser only.</p><div class="row"><input value="New Top Link" id="siteName"><button class="save" onclick="alert('Saved in demo')">Save</button></div></div>`}}
function renderEditor(c,key){let title=key==="packages"?"Packages":key==="services"?"Services":"Media Servers";c.innerHTML=`<div class="panel"><h3>${title}</h3><button class="save add" onclick="addItem('${key}')">+ Add New</button>${data[key].map((x,i)=>`<div class="row">${key==="packages"?`<input value="${x[0]}" onchange="data.${key}[${i}][0]=this.value"><input value="${x[1]}" onchange="data.${key}[${i}][1]=this.value"><input value="${x[2]}" onchange="data.${key}[${i}][2]=this.value">`:`<input value="${x[0]}" onchange="data.${key}[${i}][0]=this.value"><input value="${x[1]}" onchange="data.${key}[${i}][1]=this.value">`}<button class="save" onclick="save();show('${key}')">Save</button><button class="danger" onclick="data.${key}.splice(${i},1);save();show('${key}')">Delete</button></div>`).join("")}</div>`}
function addItem(k){data[k].push(k==="packages"?["New Package","10","500"]:["New Item","Description"]);save();show(k)}function delLead(i){let x=JSON.parse(localStorage.getItem("ntl_leads")||"[]");x.splice(i,1);localStorage.setItem("ntl_leads",JSON.stringify(x));show("leads")}